
package com.firstdatacorp.services.firstvision.voicesagetext;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_TextScheduler", targetNamespace = "http://firstdatacorp.com/Services/FirstVision/VoiceSageText")
@XmlSeeAlso({
    com.firstdatacorp.services.firstvision.common.ObjectFactory.class,
    com.firstdatacorp.services.firstvision.voicesagetext.ObjectFactory.class
})
public interface ITextScheduler {


    /**
     * 
     * @param textSchedulerReq
     * @return
     *     returns com.firstdatacorp.services.firstvision.voicesagetext.TextSchedulerResp
     * @throws TextSchedulerPerformTextSchedulerFaultMsg
     */
    @WebMethod
    @WebResult(name = "TextSchedulerResp", targetNamespace = "")
    @RequestWrapper(localName = "textScheduler", targetNamespace = "http://firstdatacorp.com/Services/FirstVision/VoiceSageText", className = "com.firstdatacorp.services.firstvision.voicesagetext.TextScheduler")
    @ResponseWrapper(localName = "textSchedulerResponse", targetNamespace = "http://firstdatacorp.com/Services/FirstVision/VoiceSageText", className = "com.firstdatacorp.services.firstvision.voicesagetext.TextSchedulerResponse")
    public TextSchedulerResp textScheduler(
        @WebParam(name = "TextSchedulerReq", targetNamespace = "")
        TextSchedulerReq textSchedulerReq)
        throws TextSchedulerPerformTextSchedulerFaultMsg
    ;

}
