
package com.firstdatacorp.services.firstvision.voicesagetext;

import javax.xml.ws.WebFault;
import com.firstdatacorp.services.firstvision.common.FVApplicationFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "operation1Fault1_PerformTextSchedulerFault", targetNamespace = "http://firstdatacorp.com/Services/FirstVision/VoiceSageText")
public class TextSchedulerPerformTextSchedulerFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FVApplicationFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TextSchedulerPerformTextSchedulerFaultMsg(String message, FVApplicationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TextSchedulerPerformTextSchedulerFaultMsg(String message, FVApplicationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.firstdatacorp.services.firstvision.common.FVApplicationFault
     */
    public FVApplicationFault getFaultInfo() {
        return faultInfo;
    }

}
