
package com.firstdatacorp.services.firstvision.voicesagetext;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TextSchedulerHttpService", targetNamespace = "http://firstdatacorp.com/Services/FirstVision/VoiceSageText", wsdlLocation = "file:/D:/Softwares/JAXWS-RI/bin/FDCSMSDatapower/MD_SendText.wsdl")
public class TextSchedulerHttpService
    extends Service
{

    private final static URL TEXTSCHEDULERHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEXTSCHEDULERHTTPSERVICE_EXCEPTION;
    private final static QName TEXTSCHEDULERHTTPSERVICE_QNAME = new QName("http://firstdatacorp.com/Services/FirstVision/VoiceSageText", "TextSchedulerHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Softwares/JAXWS-RI/bin/FDCSMSDatapower/MD_SendText.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEXTSCHEDULERHTTPSERVICE_WSDL_LOCATION = url;
        TEXTSCHEDULERHTTPSERVICE_EXCEPTION = e;
    }

    public TextSchedulerHttpService() {
        super(__getWsdlLocation(), TEXTSCHEDULERHTTPSERVICE_QNAME);
    }

    public TextSchedulerHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEXTSCHEDULERHTTPSERVICE_QNAME, features);
    }

    public TextSchedulerHttpService(URL wsdlLocation) {
        super(wsdlLocation, TEXTSCHEDULERHTTPSERVICE_QNAME);
    }

    public TextSchedulerHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEXTSCHEDULERHTTPSERVICE_QNAME, features);
    }

    public TextSchedulerHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TextSchedulerHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITextScheduler
     */
    @WebEndpoint(name = "TextSchedulerHttpPort")
    public ITextScheduler getTextSchedulerHttpPort() {
        return super.getPort(new QName("http://firstdatacorp.com/Services/FirstVision/VoiceSageText", "TextSchedulerHttpPort"), ITextScheduler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITextScheduler
     */
    @WebEndpoint(name = "TextSchedulerHttpPort")
    public ITextScheduler getTextSchedulerHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://firstdatacorp.com/Services/FirstVision/VoiceSageText", "TextSchedulerHttpPort"), ITextScheduler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEXTSCHEDULERHTTPSERVICE_EXCEPTION!= null) {
            throw TEXTSCHEDULERHTTPSERVICE_EXCEPTION;
        }
        return TEXTSCHEDULERHTTPSERVICE_WSDL_LOCATION;
    }

}
