
package com.firstdata.services.common.notification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationPortType", targetNamespace = "http://com/firstdata/services/common/notification")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationPortType {


    /**
     * 
     * @param notification
     * @return
     *     returns com.firstdata.services.common.notification.NotificationResponse
     * @throws PublishNotificationFaultMsg
     */
    @WebMethod
    @WebResult(name = "notificationRespose", targetNamespace = "")
    @RequestWrapper(localName = "publish", targetNamespace = "http://com/firstdata/services/common/notification", className = "com.firstdata.services.common.notification.Publish")
    @ResponseWrapper(localName = "publishResponse", targetNamespace = "http://com/firstdata/services/common/notification", className = "com.firstdata.services.common.notification.PublishResponse")
    public NotificationResponse publish(
        @WebParam(name = "notification", targetNamespace = "")
        Notification notification)
        throws PublishNotificationFaultMsg
    ;

}
