
package com.firstdata.services.common.notification;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "publishFault1_notificationFault", targetNamespace = "http://com/firstdata/services/common/notification")
public class PublishNotificationFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotificationFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PublishNotificationFaultMsg(String message, NotificationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PublishNotificationFaultMsg(String message, NotificationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.firstdata.services.common.notification.NotificationFault
     */
    public NotificationFault getFaultInfo() {
        return faultInfo;
    }

}
